name: Enhancement request
description: Request changes to current functionality.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest improvements to Ulauncher!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the changes you want Ulauncher to implement. If you have multiple unrelated suggestions, create multiple issues.
    validations:
      required: true
  - type: checkboxes
    id: communication-guidelines
    attributes:
      label: Communication guidelines
      description: Did you read the [communication guidelines](https://github.com/Ulauncher/Ulauncher/blob/dev/CODE_OF_CONDUCT.md#general-communication-guidelines)?
      options:
        - label: I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.
          required: true
